package io.trafficpolice.capture.huc;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.ProtocolException;
import java.net.URL;
import java.security.Permission;
import java.util.List;
import java.util.Map;

/**
 * An {@code HttpURLConnection} that records its exchange (ARCHITECTURE.md §4.3).
 *
 * Generated by {@code android/capture-core/scripts/gen_huc_wrappers.py}; edit the script, not
 * this file. Every method either delegates or goes through {@link HucCalls}.
 */
public final class TrackedHttpURLConnection extends HttpURLConnection {
    private final HttpURLConnection delegate;
    private final HucExchange exchange;

    public TrackedHttpURLConnection(HttpURLConnection delegate) {
        super(delegate.getURL());
        this.delegate = delegate;
        this.exchange = new HucExchange(delegate);
    }

    /** The wrapped connection. */
    public HttpURLConnection delegate() {
        return delegate;
    }

    @Override
    public void connect() throws IOException {
        HucCalls.connect(delegate, exchange);
    }

    @Override
    public void setConnectTimeout(int timeout) {
        delegate.setConnectTimeout(timeout);
    }

    @Override
    public int getConnectTimeout() {
        return delegate.getConnectTimeout();
    }

    @Override
    public void setReadTimeout(int timeout) {
        delegate.setReadTimeout(timeout);
    }

    @Override
    public int getReadTimeout() {
        return delegate.getReadTimeout();
    }

    @Override
    public URL getURL() {
        return delegate.getURL();
    }

    @Override
    public int getContentLength() {
        HucCalls.beforeGetter(exchange);
        int value = delegate.getContentLength();
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public long getContentLengthLong() {
        HucCalls.beforeGetter(exchange);
        long value = delegate.getContentLengthLong();
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public String getContentType() {
        HucCalls.beforeGetter(exchange);
        String value = delegate.getContentType();
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public String getContentEncoding() {
        HucCalls.beforeGetter(exchange);
        String value = delegate.getContentEncoding();
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public long getExpiration() {
        HucCalls.beforeGetter(exchange);
        long value = delegate.getExpiration();
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public long getDate() {
        HucCalls.beforeGetter(exchange);
        long value = delegate.getDate();
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public long getLastModified() {
        HucCalls.beforeGetter(exchange);
        long value = delegate.getLastModified();
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public String getHeaderField(String name) {
        HucCalls.beforeGetter(exchange);
        String value = delegate.getHeaderField(name);
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public Map<String, List<String>> getHeaderFields() {
        HucCalls.beforeGetter(exchange);
        Map<String, List<String>> value = delegate.getHeaderFields();
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public int getHeaderFieldInt(String name, int defaultValue) {
        HucCalls.beforeGetter(exchange);
        int value = delegate.getHeaderFieldInt(name, defaultValue);
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public long getHeaderFieldLong(String name, long defaultValue) {
        HucCalls.beforeGetter(exchange);
        long value = delegate.getHeaderFieldLong(name, defaultValue);
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public long getHeaderFieldDate(String name, long defaultValue) {
        HucCalls.beforeGetter(exchange);
        long value = delegate.getHeaderFieldDate(name, defaultValue);
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public String getHeaderFieldKey(int n) {
        HucCalls.beforeGetter(exchange);
        String value = delegate.getHeaderFieldKey(n);
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public String getHeaderField(int n) {
        HucCalls.beforeGetter(exchange);
        String value = delegate.getHeaderField(n);
        HucCalls.afterGetter(exchange);
        return value;
    }

    @Override
    public Object getContent() throws IOException {
        HucCalls.responseCode(delegate, exchange);
        return delegate.getContent();
    }

    @Override
    @SuppressWarnings("rawtypes") // URLConnection declares a raw Class[]
    public Object getContent(Class[] classes) throws IOException {
        HucCalls.responseCode(delegate, exchange);
        return delegate.getContent(classes);
    }

    @Override
    public Permission getPermission() throws IOException {
        return delegate.getPermission();
    }

    @Override
    public InputStream getInputStream() throws IOException {
        return HucCalls.getInputStream(delegate, exchange);
    }

    @Override
    public OutputStream getOutputStream() throws IOException {
        return HucCalls.getOutputStream(delegate, exchange);
    }

    @Override
    public String toString() {
        return delegate.toString();
    }

    @Override
    public void setDoInput(boolean doinput) {
        delegate.setDoInput(doinput);
    }

    @Override
    public boolean getDoInput() {
        return delegate.getDoInput();
    }

    @Override
    public void setDoOutput(boolean dooutput) {
        delegate.setDoOutput(dooutput);
    }

    @Override
    public boolean getDoOutput() {
        return delegate.getDoOutput();
    }

    @Override
    public void setAllowUserInteraction(boolean allowuserinteraction) {
        delegate.setAllowUserInteraction(allowuserinteraction);
    }

    @Override
    public boolean getAllowUserInteraction() {
        return delegate.getAllowUserInteraction();
    }

    @Override
    public void setUseCaches(boolean usecaches) {
        delegate.setUseCaches(usecaches);
    }

    @Override
    public boolean getUseCaches() {
        return delegate.getUseCaches();
    }

    @Override
    public void setIfModifiedSince(long ifmodifiedsince) {
        delegate.setIfModifiedSince(ifmodifiedsince);
    }

    @Override
    public long getIfModifiedSince() {
        return delegate.getIfModifiedSince();
    }

    @Override
    public boolean getDefaultUseCaches() {
        return delegate.getDefaultUseCaches();
    }

    @Override
    public void setDefaultUseCaches(boolean defaultusecaches) {
        delegate.setDefaultUseCaches(defaultusecaches);
    }

    @Override
    public void setRequestProperty(String key, String value) {
        delegate.setRequestProperty(key, value);
    }

    @Override
    public void addRequestProperty(String key, String value) {
        delegate.addRequestProperty(key, value);
    }

    @Override
    public String getRequestProperty(String key) {
        return delegate.getRequestProperty(key);
    }

    @Override
    public Map<String, List<String>> getRequestProperties() {
        return delegate.getRequestProperties();
    }

    @Override
    public void setFixedLengthStreamingMode(int contentLength) {
        delegate.setFixedLengthStreamingMode(contentLength);
    }

    @Override
    public void setFixedLengthStreamingMode(long contentLength) {
        delegate.setFixedLengthStreamingMode(contentLength);
    }

    @Override
    public void setChunkedStreamingMode(int chunklen) {
        delegate.setChunkedStreamingMode(chunklen);
    }

    @Override
    public void setInstanceFollowRedirects(boolean followRedirects) {
        delegate.setInstanceFollowRedirects(followRedirects);
    }

    @Override
    public boolean getInstanceFollowRedirects() {
        return delegate.getInstanceFollowRedirects();
    }

    @Override
    public void setRequestMethod(String method) throws ProtocolException {
        delegate.setRequestMethod(method);
    }

    @Override
    public String getRequestMethod() {
        return delegate.getRequestMethod();
    }

    @Override
    public int getResponseCode() throws IOException {
        return HucCalls.responseCode(delegate, exchange);
    }

    @Override
    public String getResponseMessage() throws IOException {
        return HucCalls.responseMessage(delegate, exchange);
    }

    @Override
    public void disconnect() {
        delegate.disconnect();
        exchange.disconnected();
    }

    @Override
    public boolean usingProxy() {
        return delegate.usingProxy();
    }

    @Override
    public InputStream getErrorStream() {
        return HucCalls.getErrorStream(delegate, exchange);
    }
}
